
<?php
if (!defined('ABSPATH')) { exit; }

function hrt_currency_symbol() {
    $cur = get_option('hr_currency', 'PHP');
    switch (strtoupper($cur)) {
        case 'USD': return '$'; case 'EUR': return '€'; case 'GBP': return '£'; case 'JPY': return '¥'; case 'PHP': default: return '₱';
    }
}
function hrt_format_price($amount) { $symbol = hrt_currency_symbol(); $dec = get_option('hr_price_decimals', 2); return $symbol . number_format((float)$amount, (int)$dec); }

class HRT_Helpers {
    public static function valid_dates($checkin, $checkout) {
        $ci = strtotime($checkin); $co = strtotime($checkout); if(!$ci||!$co) return false; $today = strtotime(date('Y-m-d')); if($ci < $today) return false; if($co <= $ci) return false; $n = self::count_nights($checkin,$checkout); return ($n>0 && $n<=90); }
    public static function count_nights($checkin, $checkout) { $ci=new DateTime($checkin); $co=new DateTime($checkout); return (int)$ci->diff($co)->format('%a'); }
    public static function dates_overlap($start1, $end1, $start2, $end2) { $s1=strtotime($start1); $e1=strtotime($end1); $s2=strtotime($start2); $e2=strtotime($end2); return ($s1 < $e2) && ($s2 < $e1); }

    public static function room_type_availability($type_id, $checkin, $checkout) {
        $qty = (int)get_post_meta($type_id,'hr_quantity',true); if($qty<1)$qty=1; $q=new WP_Query(['post_type'=>'hrt_booking','post_status'=>'publish','posts_per_page'=>-1,'fields'=>'ids','meta_query'=>[['key'=>'hr_room_type_id','value'=>$type_id,'compare'=>'='],['key'=>'hr_status','value'=>['pending','pending_payment','confirmed'],'compare'=>'IN']]]); $booked=0; if($q->posts){ foreach($q->posts as $bid){ $b_ci=get_post_meta($bid,'hr_checkin',true); $b_co=get_post_meta($bid,'hr_checkout',true); if(self::dates_overlap($checkin,$checkout,$b_ci,$b_co)) $booked++; } } $remaining=max(0,$qty-$booked); return ['available'=>($remaining>0),'remaining'=>$remaining,'booked'=>$booked]; }

    public static function calculate_total_best_rate($type_id, $checkin, $checkout) {
        $n=self::count_nights($checkin,$checkout); if($n<=0) return 0.0; $base=(float)get_post_meta($type_id,'hr_price_per_night',true); $seasons=get_post_meta($type_id,'hr_seasons',true); if(!is_array($seasons)) $seasons=[]; $weekly=(float)get_post_meta($type_id,'hr_weekly_rate',true); $monthly=(float)get_post_meta($type_id,'hr_monthly_rate',true); $dates=[]; $cur=new DateTime($checkin); $end=new DateTime($checkout); while($cur<$end){ $dates[]=$cur->format('Y-m-d'); $cur->modify('+1 day'); } $nightly=[]; foreach($dates as $d){ $price=$base; foreach($seasons as $row){ $s=$row['start']??''; $e=$row['end']??''; $p=isset($row['price'])?(float)$row['price']:0.0; if($s&&$e&&$p>0&&$d>=$s&&$d<$e){ $price=$p; break; } } $nightly[]=$price; } $pref=[0]; foreach($nightly as $i=>$v){ $pref[]=$pref[$i]+(float)$v; } $sum=function($l,$r)use($pref){ return $pref[$r]-$pref[$l]; }; $dp=array_fill(0,$n+1,0.0); for($i=$n-1;$i>=0;$i--){ $best=$nightly[$i]+$dp[$i+1]; if($weekly>0 && $i+7<=$n){ $best=min($best, min($weekly,$sum($i,$i+7))+$dp[$i+7]); } if($monthly>0 && $i+30<=$n){ $best=min($best, min($monthly,$sum($i,$i+30))+$dp[$i+30]); } $dp[$i]=$best; } return (float)$dp[0]; }

    public static function season_min_nights_check($type_id, $checkin, $checkout) {
        $seasons=get_post_meta($type_id,'hr_seasons',true); if(!is_array($seasons)) $seasons=[]; $mode=get_option('hr_min_nights_mode','arrival_only'); $n=self::count_nights($checkin,$checkout); if($n<=0) return ['ok'=>false,'message'=>__('Invalid dates.','hotel-reservation-lite')]; $countOverlap=function($s,$e)use($checkin,$checkout){ $start=max(strtotime($s),strtotime($checkin)); $end=min(strtotime($e),strtotime($checkout)); if($start>=$end) return 0; $d1=new DateTime(date('Y-m-d',$start)); $d2=new DateTime(date('Y-m-d',$end)); return (int)$d1->diff($d2)->format('%a'); }; if($mode==='arrival_only'){ $d=$checkin; foreach($seasons as $row){ $s=$row['start']??''; $e=$row['end']??''; $min=(int)($row['min']??0); if($min>0&&$s&&$e&&$d>=$s&&$d<$e){ if($n<$min) return ['ok'=>false,'message'=>sprintf(__('Minimum %d nights apply for selected dates.','hotel-reservation-lite'),$min)]; break; } } return ['ok'=>true,'message'=>'']; } foreach($seasons as $row){ $s=$row['start']??''; $e=$row['end']??''; $min=(int)($row['min']??0); if($min>0&&$s&&$e){ $k=$countOverlap($s,$e); if($k>0&&$k<$min) return ['ok'=>false,'message'=>sprintf(__('Nights inside %s require at least %d nights (you selected %d).','hotel-reservation-lite'), esc_html($row['label']??__('season','hotel-reservation-lite')),$min,$k)]; } } return ['ok'=>true,'message'=>'']; }

    public static function season_max_nights_check($type_id, $checkin, $checkout) {
        $seasons=get_post_meta($type_id,'hr_seasons',true); if(!is_array($seasons)) $seasons=[]; $mode=get_option('hr_max_nights_mode','arrival_only'); $n=self::count_nights($checkin,$checkout); if($n<=0) return ['ok'=>false,'message'=>__('Invalid dates.','hotel-reservation-lite')]; $countOverlap=function($s,$e)use($checkin,$checkout){ $start=max(strtotime($s),strtotime($checkin)); $end=min(strtotime($e),strtotime($checkout)); if($start>=$end) return 0; $d1=new DateTime(date('Y-m-d',$start)); $d2=new DateTime(date('Y-m-d',$end)); return (int)$d1->diff($d2)->format('%a'); }; if($mode==='arrival_only'){ $d=$checkin; foreach($seasons as $row){ $s=$row['start']??''; $e=$row['end']??''; $max=(int)($row['max']??0); if($max>0&&$s&&$e&&$d>=$s&&$d<$e){ if($n>$max) return ['ok'=>false,'message'=>sprintf(__('Maximum %d nights allowed for selected dates.','hotel-reservation-lite'),$max)]; break; } } return ['ok'=>true,'message'=>'']; } foreach($seasons as $row){ $s=$row['start']??''; $e=$row['end']??''; $max=(int)($row['max']??0); if($max>0&&$s&&$e){ $k=$countOverlap($s,$e); if($k>$max) return ['ok'=>false,'message'=>sprintf(__('Nights inside %s are limited to %d nights (you selected %d).','hotel-reservation-lite'), esc_html($row['label']??__('season','hotel-reservation-lite')),$max,$k)]; } } return ['ok'=>true,'message'=>'']; }

    public static function closed_out_check($type_id, $checkin, $checkout) {
        $closed=get_post_meta($type_id,'hr_closed_out',true); if(!is_array($closed)) $closed=[]; foreach($closed as $row){ $label=$row['label']??''; $s=$row['start']??''; $e=$row['end']??''; $rule=$row['rule']??'no_stay'; if(!$s||!$e) continue; if($rule==='no_arrival'){ if($checkin>=$s && $checkin<$e) return ['ok'=>false,'message'=>sprintf(__('Arrivals are closed for %s.','hotel-reservation-lite'), $label?esc_html($label):__('selected dates','hotel-reservation-lite'))]; } elseif($rule==='no_departure'){ if($checkout>=$s && $checkout<$e) return ['ok'=>false,'message'=>sprintf(__('Departures are closed for %s.','hotel-reservation-lite'), $label?esc_html($label):__('selected dates','hotel-reservation-lite'))]; } else { if(self::dates_overlap($checkin,$checkout,$s,$e)) return ['ok'=>false,'message'=>sprintf(__('Stays are closed for %s.','hotel-reservation-lite'), $label?esc_html($label):__('selected dates','hotel-reservation-lite'))]; } } return ['ok'=>true,'message'=>'']; }
}
